### ISSUE TITLE
Symbol table request for missing Ubuntu ISF (5.4.0-33 and 4.15.0-142)

### ISSUE THREAD

**Issue by indtia** [Abyss-W4tcher/volatility3-symbols#27]
dear sir, thanks for your contribution.
request if you could also send or include the symbol for these banners below mentioned banners, these are required for my academic research project.
1. Linux version 5.4.0-33-generic (buildd@lcy01-amd64-022) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 (Ubuntu 5.4.0-33.37-generic 5.4.34)
2. linux version 4.15.0-142-generic

**Comment by Abyss-W4tcher** [comment]
_This answer is valid for both of your queries._

Hello @indtia, 

Unfortunately, you came against one of the Ubuntu kernels that haven't been released in the [ddeb debug sources](http://ddebs.ubuntu.com/). Doing so, it isn't available in this repository, as it only fetch and build Ubuntu ISF from this (stable) source.

You have two solutions, one is pointed in the [Readme](https://github.com/Abyss-W4tcher/volatility3-symbols#faq) : 

 - Fetch the debug symbols from the Ubuntu kernel team, and build the ISF with [dwarf2json](https://github.com/volatilityfoundation/dwarf2json) : https://answers.launchpad.net/ubuntu/focal/amd64/linux-image-unsigned-5.4.0-33-generic-dbgsym/5.4.0-33.37 

- Use Volatility2 (deprecated, non-recommended) : https://github.com/Abyss-W4tcher/volatility2-profiles/tree/master/Ubuntu/amd64/5.4.0/33/generic

As a side note, I cannot build these kernels automatically, as they are considered "testing" or "unstable"....

--- 

I hope this issue will answer any other related request, good luck !

**Comment by indtia** [comment]
Hello sir, Thank you so much for your help i really appreciate it.
i got the Symbol table and it worked.

**Comment by Abyss-W4tcher** [comment]
Hi, you won't find it in the ddebs repository, as indicated in my first comment. You will have to search in the Ubuntu development team website for the *.ddeb*.

However, there is a pattern that can help you, to find the package : 

https://launchpad.net/ubuntu/{UBUNTU_VERSION}/amd64/?text={KERNEL_VERSION}-dbgsym

Applying this to kernel "5.4.0-33-generic", you first need to determine the Ubuntu version (https://launchpad.net/ubuntu/+series). Then :  

- https://answers.launchpad.net/ubuntu/focal/amd64/?text=5.4.0-33-generic-dbgsym

You'll get a list of packages, most likely to contain the *.ddeb* file (always check for the ~1GB, not the 15kB ones).

I let you search for "4.15.0-142-generic" :)

**Comment by Abyss-W4tcher** [comment]
Hi @indtia, a script automating the process is now available here : 

https://github.com/Abyss-W4tcher/volatility3-symbols/blob/master/symbols_finders/ubuntu_symbols_finder.py
