### ISSUE TITLE
Can we get symbols for Arch Linux too please?

### ISSUE THREAD

**Issue by 7Ragnarok7** [Abyss-W4tcher/volatility3-symbols#40]

**Comment by Abyss-W4tcher** [comment]
Hi, after checking a bit how Arch is organized, I wasn't able to find a reliable repository to scrap and download symbols from, for their `core` kernel releases.

Arch users tend to compile their own kernels, but if you have any informations to help getting those main releases `vmlinux`, do not hesitate to share them here 👍.

> Interesting ressources : 
> - https://lists.archlinux.org/pipermail/arch-announce/2022-February/000426.html
> - https://archlinux.org/packages/core/x86_64/linux/

**Comment by mb720** [comment]
I recently wanted to analyze an Arch Linux RAM image. It seems that the kernel used by Arch Linux still doesn't have a corresponding debug package, according to the list at [debuginfod](https://debuginfod.archlinux.org/packages), meaning we can't get the ISF from the kernel's debug symbols.

Instead, I had Claude create [a script](https://gitlab.com/bullbytes/btf_kallsyms_to_isf) that generates the ISF from `/sys/kernel/btf/vmlinux` and `/proc/kallsyms`.

Currently, I've used the script to analyze Arch Linux 6.19.9 with Volatility 3, version 2.27.0.
