### ISSUE TITLE
vmlinuz-6.6.9-amd64

### ISSUE THREAD

**Issue by palmieri0884** [Abyss-W4tcher/volatility3-symbols#48]
I’m having problem to create the json file for this kernel version of kali linux it is possible to help me with this?

**Comment by Abyss-W4tcher** [comment]
Hi ! 

I checked the logs, and the builder failed to create an ISF for this version. This seems to be a known bug : 

https://groups.google.com/g/linux.debian.bugs.dist/c/MCo7ckVvOTk

Indeed, the `vmlinux` is stripped from debug symbols, and fatally, unusable...

**Comment by palmieri0884** [comment]
Ok thanks. just other question to do the symbols on linux 6.1.58-v8+ aarch64 I'll have basic the same problems?

**Comment by Abyss-W4tcher** [comment]
You want to do symbols for `linux 6.1.58-v8+ aarch64` or on a `linux 6.1.58-v8+ aarch64` machine ? 

You should be able to get the dbgsym `.deb` package, extract it and use dwarf2json on the `vmlinux` file.

**Comment by palmieri0884** [comment]
Is it for the Raspberry Pi5 kali Linux 2023.3

**Comment by Abyss-W4tcher** [comment]
You should be good to go, just follow the normal procedure, by installing package `linux-image-`uname -r`-dbg` or equivalent and create the ISF 👍
